### ISSUE TITLE
Надо определиться с API

### ISSUE THREAD

**Issue by nekr0z** [sadmadrus/chessBox#3]
Предлагаю определиться с тем, как пользователи будут взаимодействовать с нашей системой. Вариантов много, и в перспективе можно и все их реализовать при желании, но с чего-то надо начинать — хотя бы в целях интергационного тестирования.

Варианты:
1. **API через HTTP** (REST, gRPC, что-то ещё — как придумаем);
  - **плюсы**:
    - можно всё сделать так, как сочтём удобным, расширяя API по необходимости;
    - потом удобно прикручивать веб-интерфейс , как у [Lichess](https://lichess.org) или [Chess.com](https://chess.com), только попроще;
  -  **минусы:**
    - надо садиться и описывать (в смысле, придумывать) API;
    - придётся самим написать какой-то базовый клиент;
    - веб-интерфейс тоже потом придётся писать самим;
2. **ICS-совместимый Telnet-интерфейс** как часть системы;
  - **плюсы**:
    - готовые графические клиенты ([XBoard](https://www.gnu.org/software/xboard/), [PyChess](https://pychess.github.io/), [ChessX](https://sourceforge.net/projects/chessx/) и ещё не меньше дюжины под разные платформы;
    - API в общем-то уже есть, не надо ничего придумывать;
    - веб-клиенты существуют тоже, в том числе на Go; веб-интерфейс готов :)
  - **минусы**:
    - протокол толком не задокументирован (впрочем, можно посмотреть на код опенсорсных клиентов, чтобы разобраться);
    - надо реализовывать всё точно так же, как у [ICC](https://www.chessclub.com/)/[FICS](https://freechess.org), иначе сторонние клиенты не заработают;
    - большинство современных клиентов используют [timeseal](https://www.unix-ag.uni-kl.de/~chess/soft/timeseal/) для синхронизации времени, придётся прикручивать и это тоже;
    - существующие реализации этого «API» (FICS, ICC, VICS) существуют довольно давно и обросли фичами; придётся методом проб и ошибок (или чтения кода) выяснять, какую минимальную часть функционала надо реализовать, чтобы заработали существующие клиенты.
3. Другие варианты?

Если идти по первому пути, возможен интересный сторонний проект: написание прокси-сервера, который будет иметь ICS-совместимый интерфейс и подключаться к нашей системе по HTTP, таким образом позволяя использовать существующие клиенты…

**Comment by sadmadrus** [comment]
Пожалуй я за первый вариант. Тем более мы его уже разбираем активно

**Comment by loskutovanl** [comment]
У меня нет преференций, так как нет опыта ни с одним из вариантов и половина аббревиатур остались непонятны.

Полгода назад трогала фронтенд, могу оказать небольшую помощь с этим делом когда дойдет

**Comment by Valentina-Khoruzhaia** [comment]
Я за первый вариант так как часто вижу в требованиях к соискателям опыт с REST и gRPC, для учебного проекта кажется хорошей идеей ориентироваться и на этот момент

**Comment by nekr0z** [comment]
Вроде решили, закроем, чтоб глаза не мозолило.
