### ISSUE TITLE
Написать валидацию доски (позиции на доске).

### ISSUE THREAD

**Issue by nekr0z** [sadmadrus/chessBox#34]

**Comment by nekr0z** [comment]
В теме проверки легальности позиции (даже если мы не берём 960) оказалось на удивление много вкусного; некоторые даже считают, что задача эта алгоритмически невыполнима.

Из курьёзов: автор этой диаграммы считает, что позиция на доске (ход белых, пешка c5 может быть взята на проходе, у чёрных доступна рокировка) не может быть достигнута легально…
![image](https://user-images.githubusercontent.com/1515080/223547899-2c9660d4-0a60-4a05-b42d-7418ee5bbe24.png)
Он, конечно, неправ — позиция абсолютно легальная и достижимая. Другой вопрос, что такая позиция, конечно, не могла бы быть достигнута в реальной игре (т.е. в такой, где хотя бы один из игроков не стремился бы именно этой позиции достичь :)

Вот это последнее соображение приводит меня к мысли, что целиться в абсолютную валидацию, может быть, и незачем; достаточно валидировать основные моменты:
1. Существует один и только один король каждого цвета.
2. Король цвета, у которого нет хода (в том смысле, что ход у другой стороны), не находится под шахом.
3. Король цвета, имеющего ход, находится под шахом не больше, чем двойным; если шах двойной, то это не два слона, не два коня, не пешка+пешка, не пешка+конь, не пешка+слон.
4. На доске не больше 8 пешек каждого цвета.
5. На горизонталях 1 и 8 пешек нет.
6. В случае, если открыто взятие на проходе, перед «проходным» полем находится пешка нужного цвета, проходное поле и поле за ним пусты.
7. Количество фигур соответствует количеству недостающих пешек: два ферзя и три ладьи одного цвета требуют не более шести пешек этого цвета на доске, и т. д. Учесть, что из двух однопольных одноцветных слонов один — проведённый.
8. Конфигурация пешек должна хотя бы примерно соответствовать количеству фигур на доске; так, 6 белых пешек на вертикали h возможны только в том случае, если у чёрных на доске не осталось ничего, кроме короля (и вряд ли такая позиция возникла в реальной игре).
9. Белые пешки на h2 и h3 означают, что белой пешки на g2 быть не может, и т.д.
10. Король не на месте не сочетается с возможностью рокировки, аналогично для ладьи.
11. Белый слон может быть заперт на 1-й горизонтали пешками только на своей стартовой позиции (т.е. невозможна позиция с белым слоном на e1 и белыми пешками на d2 и f2, например). При наличии белых пешек на d2 и f2 чёрный слон может оказаться на e1 только в результате проведения туда пешки; если белая пешка есть и на e2, чёрного слона на e1 быть не может вообще. Аналогично для 8-й горизонтали.

Есть и другие очевидно нелегальные позиции, но я не очень представляю себе, как их проверять алгоритмически. Например, вот это:
![image](https://user-images.githubusercontent.com/1515080/223546768-8debc828-4a07-4e5c-bfaf-900da462a9ab.png)
делает невозможной рокировку, а, например, вот это:
![image](https://user-images.githubusercontent.com/1515080/223552511-b6f4c730-5360-4c38-83af-c4f3baf5feeb.png)
невозможно вообще никак, но и в том, и в другом случае я не понимаю, как это проверять, не погружаясь в проверку возможности предыдущего хода, и ситуации на доске перед ним, и так далее вплоть до начальной расстановки — что выглядит совсем уж чрезмерным…

Что думаете?

**Comment by loskutovanl** [comment]
Мне кажется не нужно стремиться к абсолютной валидации позиции, главное просто проверить что нет очевидных ляпов (типа пешек на крайних рядах, кол-ва королей, шахов, позиции короля и ладьи и пешки при разрешенных рокировках и ен рассвет).

Ещё я не могу себе представить двойной шах двумя ладьями.
По сути двойной шах может быть ферзь пешка (ферзь вертикаль или горизонталь); ферзь конь; ферзь слон (ферзь вертикаль или горизонталь); ладья пешка; ладья конь; ладья слон; ферзь ладья (только если ферзь по диагонали шахует)

**Comment by loskutovanl** [comment]
В общем КМК основная цель проверки в том, что если сервис валидации хода получает доску он обратится к валидации доски и корректно выдаст статус и сообщение в логах о том что доска невалидна, вместо того чтобы пытаться валидировать ход и выдать ошибку ход невалиден когда на самом деле невалидна была доска (тот же пример про ладью которая ушла с позиции при доступной рокировке)

**Comment by nekr0z** [comment]
> Ещё я не могу себе представить двойной шах двумя ладьями.

![image](https://user-images.githubusercontent.com/1515080/223632971-3d9860ad-4b80-4c33-a532-a784d97053c1.png)
Ход белых.
После fxg=R чёрный король под двойным шахом двумя ладьями.

Аа, ну да.
С ферзем также получается.

Очень замороченно будет валидировать все случаи

**Comment by nekr0z** [comment]
> Ещё я не могу себе представить двойной шах двумя ладьями. По сути двойной шах может быть ферзь пешка (ферзь вертикаль или горизонталь); ферзь конь; ферзь слон (ферзь вертикаль или горизонталь); ладья пешка; ладья конь; ладья слон; ферзь ладья (только если ферзь по диагонали шахует)

![image](https://user-images.githubusercontent.com/1515080/223634044-f2f93dd8-efe6-4beb-a333-7f4d1eb90702.png)
Ход белых. После Ne8 имеем двойной шах конь+слон.

**Comment by da070116** [comment]
есть ещё кейс задачи-шутки, там бывает и не такое. Ради интереса полез в редактор доски на lichess, там позиция ошибочна только при нескольких королях на доске, ходе стороны, которая даёт шах, и пешках на 1/8 горизонталях. Sapienti satis?)

**Comment by nekr0z** [comment]
> Ради интереса полез в редактор доски на lichess [...]

Lichess в явном виде поддерживает 960 и Bughouse, поэтому у них так: в их редакторе пользователь, сколько мне помнится, нигде в явном виде не выбирает, для какого варианта он редактирует доску, поэтому отсекаются только такие, которые заведомо невозможны ни в каком варианте.

**Comment by da070116** [comment]
Нет, какие-то варианты правил там есть. но поскольку это всё от лукавого, даже не  разбирался, что это за правила такие

**Comment by sadmadrus** [comment]
Я думаю, что заморачиватся с валидностью расстановок на доске - идея не очень. Если какая-то комбинация возможна (хоть только в теории), то рано или поздно такая партия будет. Поэтому поддерживаю идею, что проверять нужно только очевидные ошибки на доске

**Comment by loskutovanl** [comment]
> > Ещё я не могу себе представить двойной шах двумя ладьями. По сути двойной шах может быть ферзь пешка (ферзь вертикаль или горизонталь); ферзь конь; ферзь слон (ферзь вертикаль или горизонталь); ладья пешка; ладья конь; ладья слон; ферзь ладья (только если ферзь по диагонали шахует)
> 
> ![image](https://user-images.githubusercontent.com/1515080/223634044-f2f93dd8-efe6-4beb-a333-7f4d1eb90702.png)
> Ход белых. После Ne8 имеем двойной шах конь+слон.


Да, соглашаюсь, что две ладьи и слон плюс конь возможны для двойного шаха.
Может для простоты просто проверять что шах не тройной ? ..
А то много нюансов получается для каждого варианта двойного шаха КМК

**Comment by nekr0z** [comment]
> Может для простоты просто проверять что шах не тройной ? ..

Ну, есть явно нелегальные двойные шахи — например, шах двумя пешками невозможен точно :) Но это посмотрим по ходу дела.

**Comment by nekr0z** [comment]
Написано. Для добавления проверок открыл новый тикет #41
