### ISSUE TITLE
Подход к валидации ходов

### ISSUE THREAD

**Issue by loskutovanl** [sadmadrus/chessBox#4]
Файл
https://github.com/sadmadrus/chessBox/blob/move-validation/move-validation.go

Валидация через доску или через историю ходов?

**Comment by sadmadrus** [comment]
я видел это так: 
1) проверяем допустимость хода фигурой из А в Б. Проверка на то, что фигура перемещается по правилам и ей ничего не мешает
2) проверяем игровые ситации. Для этого нужно проанализировать состояние доски в целом

**Comment by nekr0z** [comment]
Без истории ходов валидировать рокировку и en passant можно только путём навешивания на соответствующие фигуры дополнительных отметок. По мне — это костыль.
С другой стороны, это позволяет обойтись только доской, без истории, что может быть приятно.

**Comment by sadmadrus** [comment]
я пока слабо представляю, как по истории оценить положение фигур

**Comment by nekr0z** [comment]
> я пока слабо представляю, как по истории оценить положение фигур

Нам всё равно где-то надо будет пилить функционал «сделать из истории положение на доске» — не исключено, что в отдельном модуле в internal, чтобы дёргать из разных мест кодовой базы.

Навскидку: загрузка отложенных партий, загрузка файлов PGN.

**Comment by nekr0z** [comment]
Слушайте, я тут погуглил и подумал: существует [FEN](https://ru.wikipedia.org/wiki/%D0%9D%D0%BE%D1%82%D0%B0%D1%86%D0%B8%D1%8F_%D0%A4%D0%BE%D1%80%D1%81%D0%B0%D0%B9%D1%82%D0%B0_%E2%80%94_%D0%AD%D0%B4%D0%B2%D0%B0%D1%80%D0%B4%D1%81%D0%B0), сделанный специально для того, чтобы содержать полную информацию о положении на доске. Собственно, диаграмма в этом формате позволяет валидировать любой ход.

Так что беру свои слова про костыль назад. Нам просто надо, чтобы в информации о доске содержалось всё, что есть в FEN.

**Comment by sadmadrus** [comment]
> > я пока слабо представляю, как по истории оценить положение фигур
> 
> Нам всё равно где-то надо будет пилить функционал «сделать из истории положение на доске» — не исключено, что в отдельном модуле в internal, чтобы дёргать из разных мест кодовой базы.
> 
> Навскидку: загрузка отложенных партий, загрузка файлов PGN.

я как раз размышлял о похожем механизме, когда думал стоит ли хранить состояние доски или восстанавливать по истории ходов

**Comment by loskutovanl** [comment]
итого, с учетом реализации доски Евгением, мы пришли к валидации через доску. Закрываю issue.
